apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-mysql
spec:
  storageClassName: standard   
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
spec:
  storageClassName: standard   
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
