apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "mysql"
  MYSQL_USER: "drupal"
  MYSQL_PASSWORD: "drupalpassword"
